<?php
/*
Plugin Name: Virtual Robots.txt
Plugin URI: https://www.littlebizzy.com/plugins/virtual-robotstxt
Description: Replaces the default virtual robots.txt generated by WordPress with an editable one, and deletes any physical robots.txt file that may already exist.
Version: 1.0.1
Author: LittleBizzy
Author URI: https://www.littlebizzy.com

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

Copyright 2016 by LittleBizzy

*/


/* Initialization */

// Avoid script calls via plugin URL
if (!function_exists('add_action'))
	die;

// This plugin constants
define('VRTRBT_FILE', __FILE__);
define('VRTRBT_PATH', dirname(VRTRBT_FILE));
define('VRTRBT_VERSION', '1.0');


/* Robots page hook */

// WP parse query hook
add_action('parse_query', 'vrtrbt_parse_query', 0);

// WP parse query handler
function vrtrbt_parse_query($wp_query) {
	if ($wp_query->is_main_query() && $wp_query->is_robots) {
		require_once(VRTRBT_PATH.'/core/robots.php');
		VRTRBT_Core_Robots::output();
	}
}


/* Admin area */

// Only admin from here
if (!is_admin())
	return;

// Admin menu hook
add_action('admin_menu', 'vrtrbt_admin_menu');

// Create item in options menu
function vrtrbt_admin_menu() {
	add_submenu_page('options-general.php', 'Robots.txt', 'Robots.txt', 'manage_options', 'robotstxt', 'vrtrbt_admin_page');
}

// Admin page form
function vrtrbt_admin_page() {
	require_once(VRTRBT_PATH.'/admin/admin.php');
	VRTRBT_Admin::form();
}


/* Activation hooks */

// Plugin activation
register_activation_hook(VRTRBT_FILE, 'vrtrbt_activation');
function vrtrbt_activation() {
	require_once(VRTRBT_PATH.'/core/robots.php');
	VRTRBT_Core_Robots::activation();
}

// Plugin uninstall (aka remove)
register_uninstall_hook(VRTRBT_FILE, 'vrtrbt_uninstall');
function vrtrbt_uninstall() {
	require_once(VRTRBT_PATH.'/core/robots.php');
	VRTRBT_Core_Robots::uninstall();
}
